import Dr1 from "./Dr1.jpj"
import Dr2 from "./Dr2.jpj"
import Dr3 from "./Dr3.jpj"
import Dr4 from "./Dr4.jpj"
import Chat from "./Chat.png"
import Close from "./Close.svg"
import corner from "./corner.svg"
import Home from "./Home.svg"
import Insta from "./Insta.svg"
import Linkdin from "./Linkdin.svg"
import Login from "./Login.svg"
import Logo from "./Logo.svg"
import Mail from "./Mail.svg"
import MedicalMitraLogo from "./MedicalMitraLogo.svg"
import WhatsappLogo from "./WhatsappLogo.svg"
export {Dr1,Dr2,Dr3,Dr4,Chat,Close,corner,Home,Insta,Linkdin,Login,Logo,Mail,MedicalMitraLogo,WhatsappLogo}